CREATE DATABASE SENAI_HROADS_MANHA;

USE SENAI_HROADS_MANHA;

CREATE TABLE TipoDeHabilidade
(
	idTipoHab	INT PRIMARY KEY IDENTITY
	,Tipo		VARCHAR(150) NOT NULL
);

CREATE TABLE Habilidade
(
	idHab INT PRIMARY KEY IDENTITY
	,id
);