CREATE DATABASE Locadora;

USE Locadora;

CREATE TABLE Empresas
(
	idEmpresa	INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR(150) NOT NULL
);

CREATE TABLE Marcas
(
	idMarca		INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR(150) NOT NULL
);

CREATE TABLE Modelos
(
	idModelo		INT PRIMARY KEY IDENTITY
	,Descricao		VARCHAR(150) NOT NULL
	,idMarca		INT FOREIGN KEY REFERENCES Marcas (idMarca)
);

CREATE TABLE Clientes
(
	idCliente	INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR(150) NOT NULL
	,CPF		VARCHAR(150) NOT NULL
);

CREATE TABLE Veiculos
(
	idVeiculo		INT PRIMARY KEY IDENTITY
	,Placa			VARCHAR(150) NOT NULL
	,idModelo		INT FOREIGN KEY REFERENCES Modelos (idModelo)
	,idEmpresa		INT FOREIGN KEY REFERENCES Empresas (idEmpresa)
);

CREATE TABLE Alugueis
(
	idAluguel		INT PRIMARY KEY IDENTITY
	,DataInicio		VARCHAR(150) NOT NULL
	,DataFim		VARCHAR(150) NOT NULL
	,idCliente		INT FOREIGN KEY REFERENCES Clientes (idCliente)
	,idVeiculo		INT FOREIGN KEY REFERENCES Veiculos (idVeiculo)
);
